typedef unsigned char   undefined;

typedef unsigned int    ImageBaseOffset32;
typedef unsigned char    bool;
typedef unsigned char    byte;
typedef unsigned int    dword;
typedef long long    longlong;
typedef unsigned char    uchar;
typedef unsigned int    uint;
typedef unsigned long    ulong;
typedef unsigned long long    ulonglong;
typedef unsigned char    undefined1;
typedef unsigned short    undefined2;
typedef unsigned int    undefined4;
typedef unsigned long long    undefined6;
typedef unsigned long long    undefined8;
typedef unsigned short    ushort;
typedef short    wchar_t;
typedef unsigned short    word;
typedef struct bayoActor_t bayoActor_t, *PbayoActor_t;

typedef struct bayoActorFuncs_t bayoActorFuncs_t, *PbayoActorFuncs_t;

typedef struct bayoBone_t bayoBone_t, *PbayoBone_t;

typedef struct matrix4x4_t matrix4x4_t, *Pmatrix4x4_t;

typedef struct bayoWmb_t bayoWmb_t, *PbayoWmb_t;

typedef struct bayoSamplers_t bayoSamplers_t, *PbayoSamplers_t;

typedef struct bayoMesh_t bayoMesh_t, *PbayoMesh_t;

typedef struct vector3_t vector3_t, *Pvector3_t;

typedef struct bayoContext_t bayoContext_t, *PbayoContext_t;

typedef struct bayoMotionInfos_t bayoMotionInfos_t, *PbayoMotionInfos_t;

typedef struct bayoExp_t bayoExp_t, *PbayoExp_t;

typedef struct vector4_t vector4_t, *Pvector4_t;

typedef struct matLine4_t matLine4_t, *PmatLine4_t;

typedef struct wmbHeader_t wmbHeader_t, *PwmbHeader_t;

typedef struct bayoSamplerData_t bayoSamplerData_t, *PbayoSamplerData_t;

typedef struct bayoBuffers_t bayoBuffers_t, *PbayoBuffers_t;

typedef struct bayoUnknownMeshSubstruct_t bayoUnknownMeshSubstruct_t, *PbayoUnknownMeshSubstruct_t;

typedef struct bayoMeshGeometryTable_t bayoMeshGeometryTable_t, *PbayoMeshGeometryTable_t;

typedef struct bayoGeometryDescriptor_t bayoGeometryDescriptor_t, *PbayoGeometryDescriptor_t;

typedef struct bayoContextSubStruct_t bayoContextSubStruct_t, *PbayoContextSubStruct_t;

typedef struct bayoLimits_t bayoLimits_t, *PbayoLimits_t;

typedef struct bayoInstance_t bayoInstance_t, *PbayoInstance_t;

typedef struct motHeader_t motHeader_t, *PmotHeader_t;

typedef struct bayoRecordKeyCacheItem_t bayoRecordKeyCacheItem_t, *PbayoRecordKeyCacheItem_t;

typedef struct bayoSeq_t bayoSeq_t, *PbayoSeq_t;

typedef struct bayoUnknownFloatList_t bayoUnknownFloatList_t, *PbayoUnknownFloatList_t;

typedef struct bayoTransform_t bayoTransform_t, *PbayoTransform_t;

typedef struct bayoBlendAnimSubstruct_t bayoBlendAnimSubstruct_t, *PbayoBlendAnimSubstruct_t;

typedef struct bayoMotionInfosSubstruct_t bayoMotionInfosSubstruct_t, *PbayoMotionInfosSubstruct_t;

typedef struct bayoVertexBuffer_t bayoVertexBuffer_t, *PbayoVertexBuffer_t;

typedef struct bayoBatch_t bayoBatch_t, *PbayoBatch_t;

typedef struct bayoTextureCacheItem_t bayoTextureCacheItem_t, *PbayoTextureCacheItem_t;

typedef struct bayoMeshGeometryTableSubstruct_t bayoMeshGeometryTableSubstruct_t, *PbayoMeshGeometryTableSubstruct_t;

typedef struct bayoVertexBufferCacheItem_t bayoVertexBufferCacheItem_t, *PbayoVertexBufferCacheItem_t;

typedef struct bayoIndexStream_t bayoIndexStream_t, *PbayoIndexStream_t;

typedef struct bayoMaterialVectorTableItem_t bayoMaterialVectorTableItem_t, *PbayoMaterialVectorTableItem_t;

typedef struct wmbMaterial_t wmbMaterial_t, *PwmbMaterial_t;

typedef struct bayoTex_t bayoTex_t, *PbayoTex_t;

typedef struct bayoMaterialFuncTable_t bayoMaterialFuncTable_t, *PbayoMaterialFuncTable_t;

typedef struct bayoFuncs_t bayoFuncs_t, *PbayoFuncs_t;

typedef struct D3DXIMAGE_INFO D3DXIMAGE_INFO, *PD3DXIMAGE_INFO;

struct matLine4_t {
    float v1;
    float v2;
    float v3;
    float v4;
};

struct matrix4x4_t {
    struct matLine4_t a;
    struct matLine4_t b;
    struct matLine4_t c;
    struct matLine4_t d;
};

struct bayoSamplers_t {
    void * wtbHandle;
    struct bayoSamplerData_t * pSamplers;
    uint samplerCount;
    dword field_C;
};

struct vector4_t {
    float x;
    float y;
    float z;
    float w;
};

struct bayoUnknownFloatList_t {
    int present[16];
    float values[16];
};

struct bayoSeq_t {
    void * seqHandle;
    dword flags0;
    dword flags1;
    float previousDate;
    float date;
    float lastFrame;
};

struct bayoMotionInfosSubstruct_t {
    dword field_0;
    void * unknownPtr;
    uint unknownTag;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    dword field_20;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    dword field_38;
    dword field_3C;
    dword field_40;
    dword field_44;
};

struct bayoMotionInfos_t {
    struct bayoActor_t * actor;
    struct motHeader_t * motHandle;
    struct bayoRecordKeyCacheItem_t * cachedKeys;
    dword boneSymmetryStructCount;
    struct bayoInstance_t * * bayoInstance;
    float motionDate;
    float previousDate;
    float penultimateDate;
    dword nextFrameIndex;
    dword previousFrameIndex;
    float slerpRatio;
    dword bInterpolate;
    short * pWmbSymmetries;
    dword field_34;
    dword field_38;
    dword field_3C;
    struct bayoSeq_t seqStruct;
    dword field_58;
    dword field_5C;
    struct bayoUnknownFloatList_t unknownFloatList;
    float animFramePerSecond;
    dword field_E4;
    dword field_E8;
    dword field_EC;
    float frameFraction;
    float dateDelta;
    float speedDelay;
    dword flags; /* 0x2 mirror using bone symmetries (track other bone movement using pKeys)
0x4 motion blending
0x8 motion parent blending
0x40 special framerate?
0x100 integer date only
0x200 inited unknown float list?
0x400 interpolate translate and scaling
0x800 apply base bone scale?
0x10000 apply mot translate
0x20000 apply mot scale
0x40000 apply mot rotate */
    int bAnimFinished;
    byte cameraIndex; /* linked to bone cameraIndex+3936 (0xF60) and on in motions */
    byte field_105;
    byte field_106;
    byte field_107;
    dword field_108;
    dword field_10C;
    struct vector4_t baseBoneTranslate;
    struct vector4_t rootBoneTranslate;
    struct vector4_t baseToRootBoneTranslate;
    struct vector4_t baseBoneRotate;
    struct vector4_t rootBoneRotate;
    struct vector4_t baseToRootBoneRotate;
    struct vector4_t baseBoneScale;
    struct vector4_t rootBoneScale;
    struct vector4_t baseToRootBoneScale;
    struct bayoTransform_t * transforms;
    struct bayoBlendAnimSubstruct_t * pBlendedAnims;
    byte blendedAnimsCount;
    byte blendAnimCount;
    byte field_1AA;
    byte field_1AB;
    uint unknownFlags; /* 0x1 : animate */
    struct bayoMotionInfosSubstruct_t unknownSubstruct1;
    struct bayoMotionInfosSubstruct_t unknownSubstruct2;
    dword field_240;
};

struct bayoExp_t {
    void * expHandle;
    struct bayoActor_t * pActor;
    dword flags; /* 0x1 disable */
    float fArray[4];
    uint iArray[4];
    char fArrayCount;
    char iArrayCount;
    word field_2E;
};

struct bayoBone_t {
    struct matrix4x4_t transform;
    struct matrix4x4_t localTransformMatrix;
    struct matrix4x4_t transform3;
    struct vector4_t localPosition;
    struct vector4_t eulerAngles;
    struct vector4_t localScale;
    struct vector4_t cumulativeScale;
    float orientation;
    struct matrix4x4_t * additionalTransform;
    int globalBoneIndex;
    dword rotationOrder;
    struct bayoBone_t * parent;
    struct bayoBone_t * next_bone;
    uint flags; /* 0x1 apply scale
0x2 apply pretransform
0x4 do not apply parent transform
0x8 freeze object ?
0x10 apply orientation (rotation around y axis)
0x20 additional transform
0x800 exp related?
0x1000 exp related?
0x4000 motion animated?
0x8000 do not apply fractional transform
0x10000 apply motion transform */
    dword field_11C;
};

struct vector3_t {
    float x;
    float y;
    float z;
};

struct bayoWmb_t {
    struct wmbHeader_t * pWmbHeader;
};

struct bayoActor_t {
    struct bayoActorFuncs_t * funcs;
    void * field_4;
    void * field_8;
    uint field_C;
    struct bayoBone_t baseBone;
    struct matrix4x4_t transform;
    struct matrix4x4_t inverseTransform;
    struct bayoWmb_t wmb;
    struct matrix4x4_t * pTransformMatricesBis;
    struct matrix4x4_t * pInverseTransformMatrices;
    struct matrix4x4_t * pTransformMatrices;
    struct bayoSamplers_t samplers;
    struct bayoSamplers_t animatedSamplers;
    struct bayoMesh_t * firstMesh;
    struct bayoMesh_t * * ppMeshes;
    dword numMeshes;
    dword field_1EC;
    dword field_1F0;
    dword field_1F4;
    dword field_1F8;
    dword field_1FC;
    dword field_200;
    dword field_204;
    dword field_208;
    dword field_20C;
    dword field_210;
    dword field_214;
    dword field_218;
    dword field_21C;
    dword field_220;
    dword field_224;
    dword field_228;
    dword field_22C;
    int localNumBones;
    dword lastLocalBoneIndex;
    struct bayoBone_t * * ppBones;
    dword field_23C;
    dword field_240;
    struct vector3_t globalCorner1;
    struct vector3_t globalCorner2;
    struct vector3_t globalCenter;
    float globalHeight;
    float globalRadius;
    struct bayoBone_t * centerBone;
    dword field_274;
    dword field_278;
    dword field_27C;
    dword field_280;
    dword field_284;
    dword field_288;
    dword field_28C;
    dword field_290;
    dword field_294;
    dword field_298;
    dword field_29C;
    dword field_2A0;
    dword field_2A4;
    dword field_2A8;
    dword field_2AC;
    dword field_2B0;
    dword field_2B4;
    dword field_2B8;
    dword field_2BC;
    dword field_2C0;
    dword field_2C4;
    dword field_2C8;
    dword field_2CC;
    dword field_2D0;
    dword field_2D4;
    dword field_2D8;
    dword field_2DC;
    dword field_2E0;
    dword field_2E4;
    dword field_2E8;
    dword field_2EC;
    dword field_2F0;
    dword field_2F4;
    dword field_2F8;
    dword field_2FC;
    dword field_300;
    dword field_304;
    dword field_308;
    dword field_30C;
    dword field_310;
    dword field_314;
    dword field_318;
    dword field_31C;
    dword field_320;
    dword field_324;
    dword field_328;
    dword field_32C;
    dword field_330;
    dword field_334;
    dword field_338;
    dword field_33C;
    dword field_340;
    dword field_344;
    dword field_348;
    dword field_34C;
    dword field_350;
    dword field_354;
    int bAnimatedMaterial;
    dword field_35C;
    dword field_360;
    dword field_364;
    dword field_368;
    dword field_36C;
    dword field_370;
    dword field_374;
    dword field_378;
    dword field_37C;
    dword field_380;
    dword field_384;
    dword field_388;
    dword field_38C;
    struct bayoContext_t * bayoContext;
    dword field_394;
    dword field_398;
    dword field_39C;
    dword field_3A0;
    dword field_3A4;
    dword field_3A8;
    dword field_3AC;
    dword field_3B0;
    dword field_3B4;
    dword field_3B8;
    dword field_3BC;
    dword field_3C0;
    dword field_3C4;
    dword field_3C8;
    dword field_3CC;
    struct bayoMotionInfos_t motionInfos;
    dword field_614;
    dword field_618;
    dword field_61C;
    dword field_620;
    dword field_624;
    dword field_628;
    dword field_62C;
    dword field_630;
    dword field_634;
    dword field_638;
    dword field_63C;
    dword field_640;
    dword field_644;
    dword field_648;
    dword field_64C;
    dword field_650;
    dword field_654;
    dword field_658;
    dword field_65C;
    struct bayoExp_t bayoExp;
};

struct bayoRecordKeyCacheItem_t {
    void * pKeys;
    int index;
};

struct bayoVertexBufferCacheItem_t {
    void * pStream;
    void * pSourceStream;
    uint structSize;
    uint numVertices;
};

struct bayoVertexBuffer_t {
    struct bayoVertexBufferCacheItem_t vertexStream;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
};

struct bayoMaterialVectorTableItem_t {
    struct bayoMaterialFuncTable_t * materialFuncTable;
    dword field_4;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
};

struct bayoUnknownMeshSubstruct_t {
    dword field_0;
    dword field_4;
    struct bayoTextureCacheItem_t * animatedTexturesCacheItem;
    dword field_C;
    dword flags; /* 0x20000000 has vertexExData
0x400000 has special materials (transparent...)
0x200 don't translate bones
0x100 batch have bones */
    void * boneRefsInfosArray;
    dword field_18;
    dword field_1C;
    int two;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    dword field_38;
    dword field_3C;
    float field_40;
    float field_44;
    float field_48;
    float field_4C;
    float field_50;
    dword field_54;
    dword field_58;
    int actorField_2B4;
    dword field_60;
    float field_64;
    float field_68;
    dword field_6C;
    dword field_70;
    float field_74;
    dword field_78;
    dword field_7C;
    dword field_80;
    dword field_84;
    float field_88;
    float field_8C;
    float field_90;
    float field_94;
    dword field_98;
    dword field_9C;
    dword field_A0;
    dword field_A4;
};

struct bayoIndexStream_t {
    void * pStream;
    void * pSourceStream;
    uint structSize;
    uint numIndices;
};

struct D3DXIMAGE_INFO {
    uint Width;
    uint Height;
    uint Depth;
    uint MipLevels;
    uint Format;
    uint ResourceType;
    uint ImageFileFormat;
};

struct bayoTex_t {
    struct bayoFuncs_t * funcs;
    dword field_4;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    void * d3dtexture;
    uint type;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    dword field_38;
    dword field_3C;
    dword flags;
    struct D3DXIMAGE_INFO d3dxImageInfo;
    int bTransparent;
    int bMasked;
    int bAbsent;
};

struct wmbHeader_t {
    uint id;
    uint field_4;
    uint vertexFormat;
    uint numVertices;
    uchar numMapping;
    uchar vertexExData;
    ushort field_12;
    uint offsetPositions;
    uint offsetVertices;
    uint offsetVerticesExData;
    dword field_20;
    dword field_24;
    dword field_28;
    dword field_2C;
    uint numBones;
    uint offsetBoneHierarchy;
    uint offsetBoneRelativePositions;
    uint offsetBonePositions;
    uint offsetBoneIndexTranslateTable;
    uint numMaterials;
    uint offsetMaterialsOffsets;
    uint offsetMaterials;
    uint numMeshes;
    uint offsetMeshesOffsets;
    uint offsetMeshes;
    dword field_5C;
    dword field_60;
    uint offsetUnknown;
    uint offsetBoneSymmetries;
    uint offsetBoneFlags;
    dword field_70;
    dword field_74;
    dword field_78;
    dword field_7C;
};

struct bayoMaterialFuncTable_t {
    int (* field_0)(int *);
    int (* field_4)(int *);
    int (* field_8)(int *);
    int (* field_C)(uint *, int, char *, char *);
    uint (* field_10)(uint *, uint);
    uint (* field_14)(uint *, uint);
    int (* field_18)(int *);
};

struct bayoLimits_t {
    struct bayoInstance_t * bayoInstance;
    dword field_4;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    dword field_20;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    uint maxStructSize;
    dword field_38;
    uint meshAlignment;
    uint maxStructCount;
};

struct bayoContext_t {
    struct bayoContextSubStruct_t * pSubStruct;
    struct bayoLimits_t * * ppLimits;
    struct bayoInstance_t * * ppBayoInstance;
};

struct bayoBuffers_t {
    int maxBoneRef;
    struct bayoVertexBuffer_t positions;
    struct bayoVertexBuffer_t vertices;
    struct bayoVertexBuffer_t verticesExData;
    struct bayoVertexBuffer_t normals;
    struct bayoSamplers_t samplerInfos;
    int vertexSize;
    int numBatch;
    struct bayoBatch_t * pBatches;
    int samplerField0x60BatchCount;
    int samplerField0x64BatchCount;
    int normalBatchCount;
    struct bayoBatch_t * pLastSamplerField0x60Batch;
    struct bayoBatch_t * pLastSamplerField0x64Batch;
    struct bayoBatch_t * pLastormalBatch;
    dword field_B8;
};

struct bayoBatch_t {
    struct bayoIndexStream_t indices;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    int primitiveType;
    struct bayoMaterialVectorTableItem_t * pMaterialFuncs;
    struct wmbMaterial_t * pMaterial;
    uint vertexEnd;
    uint vertexStart;
    int vertexOffset;
    ushort flags;
    word field_3A;
    dword field_3C;
    dword field_40;
    uchar unknownE2;
    uchar unknownE1;
    byte field_46;
    byte field_47;
    uint isSamplerField0x64;
    uint isSamplerField0x60;
    uint isSpecial;
    int numBoneRefs;
    uchar * boneRefs;
    dword field_5C;
};

struct bayoTextureCacheItem_t {
    void * wtbHandle;
    struct bayoTex_t * textures;
    int textureCount;
};

struct bayoActorFuncs_t {
    dword field_0;
    dword field_4;
    __thiscall void (* func3)(struct bayoActor_t *, int);
};

struct bayoMesh_t {
    struct vector3_t hitBox;
    dword field_C;
    int totalBoneRefs;
    dword field_14;
    struct bayoMesh_t * nextMesh;
    struct vector3_t corner1;
    struct vector3_t corner2;
    struct vector3_t center;
    float height;
    float radius;
    char * pName;
    float unknown1;
    float unknown2;
    uint unknownFlags;
    int uv_value;
    dword field_5C;
    dword field_60;
    dword field_64;
    dword field_68;
    struct bayoBuffers_t * pBuffersStruct;
    struct bayoUnknownMeshSubstruct_t * pUnknownSubstruct;
    struct bayoMeshGeometryTable_t * pGeometryTable;
    struct bayoGeometryDescriptor_t * * ppGeometryDescriptor;
    dword field_7C;
    dword field_80;
    dword field_84;
    dword field_88;
    dword field_8C;
    dword field_90;
    dword field_94;
    dword field_98;
    dword field_9C;
    dword field_A0;
    dword field_A4;
    dword field_A8;
    dword field_AC;
};

struct bayoGeometryDescriptor_t {
    struct bayoBuffers_t buffers;
    struct bayoUnknownMeshSubstruct_t unknownSubstruct;
};

struct bayoBlendAnimSubstruct_t {
    void * motHandle;
    float blendAnimFraction;
    dword field_8;
    dword field_C;
    struct bayoRecordKeyCacheItem_t * cachedKeys;
    dword field_14;
    dword field_18;
    dword field_1C;
};

struct motHeader_t {
    uint id;
    ushort flags; /* 0x2 camera infos?
0x1 looping anim */
    ushort frameCount;
    uint recordOffset;
    uint recordCount;
};

struct bayoMeshGeometryTableSubstruct_t {
    void * * field_0;
    struct bayoGeometryDescriptor_t * * ppGeometryDescriptor;
    int cumulativeBatchCount;
    int numBatch;
    struct bayoBatch_t * pBatches;
    dword field_14;
};

struct bayoMeshGeometryTable_t {
    struct bayoMeshGeometryTableSubstruct_t ss_0;
    struct bayoMeshGeometryTableSubstruct_t ss_1;
    struct bayoMeshGeometryTableSubstruct_t ss_2;
    struct bayoMeshGeometryTableSubstruct_t ss_3;
    struct bayoMeshGeometryTableSubstruct_t ss_4;
    struct bayoMeshGeometryTableSubstruct_t field0x64Batches;
    struct bayoMeshGeometryTableSubstruct_t normalBatches;
    struct bayoMeshGeometryTableSubstruct_t field0x60Batches;
    struct bayoGeometryDescriptor_t * geometryDescriptor;
};

struct wmbMaterial_t {
    ushort code;
    ushort flags;
    uint sampler;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
};

struct bayoContextSubStruct_t {
    dword field_0;
    struct bayoLimits_t bayoLimits;
};

struct bayoSamplerData_t {
    dword field_0;
    dword field_4;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    dword field_20;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    dword field_38;
    dword field_3C;
    dword field_40;
    dword field_44;
    dword field_48;
    dword field_4C;
    dword field_50;
    dword field_54;
    dword field_58;
    dword field_5C;
    dword field_60;
    dword field_64;
    dword field_68;
};

struct bayoTransform_t {
    struct vector4_t localTranslate;
    struct vector4_t globalTranslate;
    struct vector4_t localRotate;
    struct vector4_t globalRotate;
    struct vector4_t localScale;
    struct vector4_t globalScale;
};

struct bayoFuncs_t {
    dword field_0;
    dword field_4;
    void * (* free)(void *);
};

struct bayoInstance_t {
    dword field_0;
    dword field_4;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    dword field_20;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    void * (* pfAllocator)(uint, uint, uint);
    dword field_3C;
    dword field_40;
    dword field_44;
    dword field_48;
    dword field_4C;
    dword field_50;
    dword field_54;
    dword field_58;
    dword field_5C;
    dword field_60;
    dword field_64;
    dword field_68;
    dword field_6C;
    dword field_70;
    dword field_74;
    dword field_78;
    dword field_7C;
    dword field_80;
    dword field_84;
    dword field_88;
    dword field_8C;
    dword field_90;
    dword field_94;
    dword field_98;
    dword field_9C;
    dword field_A0;
    dword field_A4;
    dword field_A8;
    dword field_AC;
    dword field_B0;
    dword field_B4;
    dword field_B8;
    dword field_BC;
    dword field_C0;
    dword field_C4;
    dword field_C8;
    dword field_CC;
    dword field_D0;
    dword field_D4;
    dword field_D8;
    dword field_DC;
    dword field_E0;
    dword field_E4;
};

typedef struct bayoAttachPoint_t bayoAttachPoint_t, *PbayoAttachPoint_t;

struct bayoAttachPoint_t {
    int sourceBoneIndex;
    int targetBoneIndex;
    int option;
};

typedef struct bayoBatchInfos_t bayoBatchInfos_t, *PbayoBatchInfos_t;

struct bayoBatchInfos_t {
    uint materialID;
    uint numIndices;
    uint vertexEnd;
    uint vertexStart;
    int vertexOffset;
    int primitiveType;
    ushort flags;
    uchar unknownE2;
    uchar unknownE1;
};

typedef struct bayoBlendAnimDescriptor_t bayoBlendAnimDescriptor_t, *PbayoBlendAnimDescriptor_t;

typedef struct motRecord_t motRecord_t, *PmotRecord_t;

typedef union motRecorOffVal_t motRecorOffVal_t, *PmotRecorOffVal_t;

union motRecorOffVal_t {
    uint offset;
    float fValue;
};

struct motRecord_t {
    short boneIndex;
    byte trackIndex;
    byte type;
    short elemNumber;
    short unknown;
    union motRecorOffVal_t data;
};

struct bayoBlendAnimDescriptor_t {
    struct motHeader_t * pMotHeader;
    struct motRecord_t * pMotRecords;
    float blendFraction;
    dword field_C;
    dword field_10;
    struct bayoRecordKeyCacheItem_t * cachedKeys;
};

typedef struct bayoCacheItem_t bayoCacheItem_t, *PbayoCacheItem_t;

typedef struct bayoObject_t bayoObject_t, *PbayoObject_t;

struct bayoCacheItem_t {
    void * handle;
    struct bayoObject_t * pObjects;
};

struct bayoObject_t {
    struct bayoFuncs_t * funcs;
};

typedef struct bayoCamera_t bayoCamera_t, *PbayoCamera_t;

struct bayoCamera_t {
    dword field_0;
    dword field_4;
    dword field_8;
    dword field_C;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    dword field_20;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    dword field_38;
    dword field_3C;
    dword field_40;
    dword field_44;
    dword field_48;
    dword field_4C;
    dword field_50;
    dword field_54;
    dword field_58;
    dword field_5C;
    dword field_60;
    dword field_64;
    dword field_68;
    dword field_6C;
    dword field_70;
    dword field_74;
    dword field_78;
    dword field_7C;
    dword field_80;
    dword field_84;
    dword field_88;
    dword field_8C;
    dword field_90;
    float rotateX;
    dword field_98;
    dword field_9C;
    undefined field_0xa0;
    undefined field_0xa1;
    undefined field_0xa2;
    undefined field_0xa3;
    undefined field_0xa4;
    undefined field_0xa5;
    undefined field_0xa6;
    undefined field_0xa7;
    undefined field_0xa8;
    undefined field_0xa9;
    undefined field_0xaa;
    undefined field_0xab;
    undefined field_0xac;
    undefined field_0xad;
    undefined field_0xae;
    undefined field_0xaf;
    undefined field_0xb0;
    undefined field_0xb1;
    undefined field_0xb2;
    undefined field_0xb3;
    undefined field_0xb4;
    undefined field_0xb5;
    undefined field_0xb6;
    undefined field_0xb7;
    undefined field_0xb8;
    undefined field_0xb9;
    undefined field_0xba;
    undefined field_0xbb;
    undefined field_0xbc;
    undefined field_0xbd;
    undefined field_0xbe;
    undefined field_0xbf;
    undefined field_0xc0;
    undefined field_0xc1;
    undefined field_0xc2;
    undefined field_0xc3;
    undefined field_0xc4;
    undefined field_0xc5;
    undefined field_0xc6;
    undefined field_0xc7;
    undefined field_0xc8;
    undefined field_0xc9;
    undefined field_0xca;
    undefined field_0xcb;
    undefined field_0xcc;
    undefined field_0xcd;
    undefined field_0xce;
    undefined field_0xcf;
    undefined field_0xd0;
    undefined field_0xd1;
    undefined field_0xd2;
    undefined field_0xd3;
    undefined field_0xd4;
    undefined field_0xd5;
    undefined field_0xd6;
    undefined field_0xd7;
    undefined field_0xd8;
    undefined field_0xd9;
    undefined field_0xda;
    undefined field_0xdb;
    undefined field_0xdc;
    undefined field_0xdd;
    undefined field_0xde;
    undefined field_0xdf;
    undefined field_0xe0;
    undefined field_0xe1;
    undefined field_0xe2;
    undefined field_0xe3;
    undefined field_0xe4;
    undefined field_0xe5;
    undefined field_0xe6;
    undefined field_0xe7;
    undefined field_0xe8;
    undefined field_0xe9;
    undefined field_0xea;
    undefined field_0xeb;
    undefined field_0xec;
    undefined field_0xed;
    undefined field_0xee;
    undefined field_0xef;
    undefined field_0xf0;
    undefined field_0xf1;
    undefined field_0xf2;
    undefined field_0xf3;
    undefined field_0xf4;
    undefined field_0xf5;
    undefined field_0xf6;
    undefined field_0xf7;
    undefined field_0xf8;
    undefined field_0xf9;
    undefined field_0xfa;
    undefined field_0xfb;
    undefined field_0xfc;
    undefined field_0xfd;
    undefined field_0xfe;
    undefined field_0xff;
    undefined field_0x100;
    undefined field_0x101;
    undefined field_0x102;
    undefined field_0x103;
    undefined field_0x104;
    undefined field_0x105;
    undefined field_0x106;
    undefined field_0x107;
    undefined field_0x108;
    undefined field_0x109;
    undefined field_0x10a;
    undefined field_0x10b;
    undefined field_0x10c;
    undefined field_0x10d;
    undefined field_0x10e;
    undefined field_0x10f;
    undefined field_0x110;
    undefined field_0x111;
    undefined field_0x112;
    undefined field_0x113;
    undefined field_0x114;
    undefined field_0x115;
    undefined field_0x116;
    undefined field_0x117;
    undefined field_0x118;
    undefined field_0x119;
    undefined field_0x11a;
    undefined field_0x11b;
    undefined field_0x11c;
    undefined field_0x11d;
    undefined field_0x11e;
    undefined field_0x11f;
    undefined field_0x120;
    undefined field_0x121;
    undefined field_0x122;
    undefined field_0x123;
    undefined field_0x124;
    undefined field_0x125;
    undefined field_0x126;
    undefined field_0x127;
    undefined field_0x128;
    undefined field_0x129;
    undefined field_0x12a;
    undefined field_0x12b;
    undefined field_0x12c;
    undefined field_0x12d;
    undefined field_0x12e;
    undefined field_0x12f;
    undefined field_0x130;
    undefined field_0x131;
    undefined field_0x132;
    undefined field_0x133;
    undefined field_0x134;
    undefined field_0x135;
    undefined field_0x136;
    undefined field_0x137;
    undefined field_0x138;
    undefined field_0x139;
    undefined field_0x13a;
    undefined field_0x13b;
    undefined field_0x13c;
    undefined field_0x13d;
    undefined field_0x13e;
    undefined field_0x13f;
    undefined field_0x140;
    undefined field_0x141;
    undefined field_0x142;
    undefined field_0x143;
    undefined field_0x144;
    undefined field_0x145;
    undefined field_0x146;
    undefined field_0x147;
    undefined field_0x148;
    undefined field_0x149;
    undefined field_0x14a;
    undefined field_0x14b;
    undefined field_0x14c;
    undefined field_0x14d;
    undefined field_0x14e;
    undefined field_0x14f;
    undefined field_0x150;
    undefined field_0x151;
    undefined field_0x152;
    undefined field_0x153;
    undefined field_0x154;
    undefined field_0x155;
    undefined field_0x156;
    undefined field_0x157;
    undefined field_0x158;
    undefined field_0x159;
    undefined field_0x15a;
    undefined field_0x15b;
    undefined field_0x15c;
    undefined field_0x15d;
    undefined field_0x15e;
    undefined field_0x15f;
    undefined field_0x160;
    undefined field_0x161;
    undefined field_0x162;
    undefined field_0x163;
    undefined field_0x164;
    undefined field_0x165;
    undefined field_0x166;
    undefined field_0x167;
    undefined field_0x168;
    undefined field_0x169;
    undefined field_0x16a;
    undefined field_0x16b;
    undefined field_0x16c;
    undefined field_0x16d;
    undefined field_0x16e;
    undefined field_0x16f;
    undefined field_0x170;
    undefined field_0x171;
    undefined field_0x172;
    undefined field_0x173;
    undefined field_0x174;
    undefined field_0x175;
    undefined field_0x176;
    undefined field_0x177;
    undefined field_0x178;
    undefined field_0x179;
    undefined field_0x17a;
    undefined field_0x17b;
    undefined field_0x17c;
    undefined field_0x17d;
    undefined field_0x17e;
    undefined field_0x17f;
    undefined field_0x180;
    undefined field_0x181;
    undefined field_0x182;
    undefined field_0x183;
    undefined field_0x184;
    undefined field_0x185;
    undefined field_0x186;
    undefined field_0x187;
    undefined field_0x188;
    undefined field_0x189;
    undefined field_0x18a;
    undefined field_0x18b;
    undefined field_0x18c;
    undefined field_0x18d;
    undefined field_0x18e;
    undefined field_0x18f;
    undefined field_0x190;
    undefined field_0x191;
    undefined field_0x192;
    undefined field_0x193;
    undefined field_0x194;
    undefined field_0x195;
    undefined field_0x196;
    undefined field_0x197;
    undefined field_0x198;
    undefined field_0x199;
    undefined field_0x19a;
    undefined field_0x19b;
    undefined field_0x19c;
    undefined field_0x19d;
    undefined field_0x19e;
    undefined field_0x19f;
    undefined field_0x1a0;
    undefined field_0x1a1;
    undefined field_0x1a2;
    undefined field_0x1a3;
    undefined field_0x1a4;
    undefined field_0x1a5;
    undefined field_0x1a6;
    undefined field_0x1a7;
    undefined field_0x1a8;
    undefined field_0x1a9;
    undefined field_0x1aa;
    undefined field_0x1ab;
    undefined field_0x1ac;
    undefined field_0x1ad;
    undefined field_0x1ae;
    undefined field_0x1af;
    undefined field_0x1b0;
    undefined field_0x1b1;
    undefined field_0x1b2;
    undefined field_0x1b3;
    undefined field_0x1b4;
    undefined field_0x1b5;
    undefined field_0x1b6;
    undefined field_0x1b7;
    undefined field_0x1b8;
    undefined field_0x1b9;
    undefined field_0x1ba;
    undefined field_0x1bb;
    undefined field_0x1bc;
    undefined field_0x1bd;
    undefined field_0x1be;
    undefined field_0x1bf;
    undefined field_0x1c0;
    undefined field_0x1c1;
    undefined field_0x1c2;
    undefined field_0x1c3;
    undefined field_0x1c4;
    undefined field_0x1c5;
    undefined field_0x1c6;
    undefined field_0x1c7;
    undefined field_0x1c8;
    undefined field_0x1c9;
    undefined field_0x1ca;
    undefined field_0x1cb;
    undefined field_0x1cc;
    undefined field_0x1cd;
    undefined field_0x1ce;
    undefined field_0x1cf;
    undefined field_0x1d0;
    undefined field_0x1d1;
    undefined field_0x1d2;
    undefined field_0x1d3;
    undefined field_0x1d4;
    undefined field_0x1d5;
    undefined field_0x1d6;
    undefined field_0x1d7;
    undefined field_0x1d8;
    undefined field_0x1d9;
    undefined field_0x1da;
    undefined field_0x1db;
    undefined field_0x1dc;
    undefined field_0x1dd;
    undefined field_0x1de;
    undefined field_0x1df;
    undefined field_0x1e0;
    undefined field_0x1e1;
    undefined field_0x1e2;
    undefined field_0x1e3;
    undefined field_0x1e4;
    undefined field_0x1e5;
    undefined field_0x1e6;
    undefined field_0x1e7;
    undefined field_0x1e8;
    undefined field_0x1e9;
    undefined field_0x1ea;
    undefined field_0x1eb;
    undefined field_0x1ec;
    undefined field_0x1ed;
    undefined field_0x1ee;
    undefined field_0x1ef;
    undefined field_0x1f0;
    undefined field_0x1f1;
    undefined field_0x1f2;
    undefined field_0x1f3;
    undefined field_0x1f4;
    undefined field_0x1f5;
    undefined field_0x1f6;
    undefined field_0x1f7;
    undefined field_0x1f8;
    undefined field_0x1f9;
    undefined field_0x1fa;
    undefined field_0x1fb;
    undefined field_0x1fc;
    undefined field_0x1fd;
    undefined field_0x1fe;
    undefined field_0x1ff;
    undefined field_0x200;
    undefined field_0x201;
    undefined field_0x202;
    undefined field_0x203;
    undefined field_0x204;
    undefined field_0x205;
    undefined field_0x206;
    undefined field_0x207;
    undefined field_0x208;
    undefined field_0x209;
    undefined field_0x20a;
    undefined field_0x20b;
    undefined field_0x20c;
    undefined field_0x20d;
    undefined field_0x20e;
    undefined field_0x20f;
    undefined field_0x210;
    undefined field_0x211;
    undefined field_0x212;
    undefined field_0x213;
    undefined field_0x214;
    undefined field_0x215;
    undefined field_0x216;
    undefined field_0x217;
    undefined field_0x218;
    undefined field_0x219;
    undefined field_0x21a;
    undefined field_0x21b;
    undefined field_0x21c;
    undefined field_0x21d;
    undefined field_0x21e;
    undefined field_0x21f;
    undefined field_0x220;
    undefined field_0x221;
    undefined field_0x222;
    undefined field_0x223;
    undefined field_0x224;
    undefined field_0x225;
    undefined field_0x226;
    undefined field_0x227;
    undefined field_0x228;
    undefined field_0x229;
    undefined field_0x22a;
    undefined field_0x22b;
    undefined field_0x22c;
    undefined field_0x22d;
    undefined field_0x22e;
    undefined field_0x22f;
    undefined field_0x230;
    undefined field_0x231;
    undefined field_0x232;
    undefined field_0x233;
    undefined field_0x234;
    undefined field_0x235;
    undefined field_0x236;
    undefined field_0x237;
    undefined field_0x238;
    undefined field_0x239;
    undefined field_0x23a;
    undefined field_0x23b;
    undefined field_0x23c;
    undefined field_0x23d;
    undefined field_0x23e;
    undefined field_0x23f;
    undefined field_0x240;
    undefined field_0x241;
    undefined field_0x242;
    undefined field_0x243;
    undefined field_0x244;
    undefined field_0x245;
    undefined field_0x246;
    undefined field_0x247;
    undefined field_0x248;
    undefined field_0x249;
    undefined field_0x24a;
    undefined field_0x24b;
    undefined field_0x24c;
    undefined field_0x24d;
    undefined field_0x24e;
    undefined field_0x24f;
    undefined field_0x250;
    undefined field_0x251;
    undefined field_0x252;
    undefined field_0x253;
    undefined field_0x254;
    undefined field_0x255;
    undefined field_0x256;
    undefined field_0x257;
    undefined field_0x258;
    undefined field_0x259;
    undefined field_0x25a;
    undefined field_0x25b;
    undefined field_0x25c;
    undefined field_0x25d;
    undefined field_0x25e;
    undefined field_0x25f;
    undefined field_0x260;
    undefined field_0x261;
    undefined field_0x262;
    undefined field_0x263;
    undefined field_0x264;
    undefined field_0x265;
    undefined field_0x266;
    undefined field_0x267;
    undefined field_0x268;
    undefined field_0x269;
    undefined field_0x26a;
    undefined field_0x26b;
    undefined field_0x26c;
    undefined field_0x26d;
    undefined field_0x26e;
    undefined field_0x26f;
    undefined field_0x270;
    undefined field_0x271;
    undefined field_0x272;
    undefined field_0x273;
    undefined field_0x274;
    undefined field_0x275;
    undefined field_0x276;
    undefined field_0x277;
    undefined field_0x278;
    undefined field_0x279;
    undefined field_0x27a;
    undefined field_0x27b;
    undefined field_0x27c;
    undefined field_0x27d;
    undefined field_0x27e;
    undefined field_0x27f;
    undefined field_0x280;
    undefined field_0x281;
    undefined field_0x282;
    undefined field_0x283;
    undefined field_0x284;
    undefined field_0x285;
    undefined field_0x286;
    undefined field_0x287;
    undefined field_0x288;
    undefined field_0x289;
    undefined field_0x28a;
    undefined field_0x28b;
    undefined field_0x28c;
    undefined field_0x28d;
    undefined field_0x28e;
    undefined field_0x28f;
    undefined field_0x290;
    undefined field_0x291;
    undefined field_0x292;
    undefined field_0x293;
    undefined field_0x294;
    undefined field_0x295;
    undefined field_0x296;
    undefined field_0x297;
    undefined field_0x298;
    undefined field_0x299;
    undefined field_0x29a;
    undefined field_0x29b;
    undefined field_0x29c;
    undefined field_0x29d;
    undefined field_0x29e;
    undefined field_0x29f;
    undefined field_0x2a0;
    undefined field_0x2a1;
    undefined field_0x2a2;
    undefined field_0x2a3;
    undefined field_0x2a4;
    undefined field_0x2a5;
    undefined field_0x2a6;
    undefined field_0x2a7;
    undefined field_0x2a8;
    undefined field_0x2a9;
    undefined field_0x2aa;
    undefined field_0x2ab;
    undefined field_0x2ac;
    undefined field_0x2ad;
    undefined field_0x2ae;
    undefined field_0x2af;
    undefined field_0x2b0;
    undefined field_0x2b1;
    undefined field_0x2b2;
    undefined field_0x2b3;
    undefined field_0x2b4;
    undefined field_0x2b5;
    undefined field_0x2b6;
    undefined field_0x2b7;
    undefined field_0x2b8;
    undefined field_0x2b9;
    undefined field_0x2ba;
    undefined field_0x2bb;
    undefined field_0x2bc;
    undefined field_0x2bd;
    undefined field_0x2be;
    undefined field_0x2bf;
    undefined field_0x2c0;
    undefined field_0x2c1;
    undefined field_0x2c2;
    undefined field_0x2c3;
    undefined field_0x2c4;
    undefined field_0x2c5;
    undefined field_0x2c6;
    undefined field_0x2c7;
    undefined field_0x2c8;
    undefined field_0x2c9;
    undefined field_0x2ca;
    undefined field_0x2cb;
    undefined field_0x2cc;
    undefined field_0x2cd;
    undefined field_0x2ce;
    undefined field_0x2cf;
    undefined field_0x2d0;
    undefined field_0x2d1;
    undefined field_0x2d2;
    undefined field_0x2d3;
    undefined field_0x2d4;
    undefined field_0x2d5;
    undefined field_0x2d6;
    undefined field_0x2d7;
    undefined field_0x2d8;
    undefined field_0x2d9;
    undefined field_0x2da;
    undefined field_0x2db;
    undefined field_0x2dc;
    undefined field_0x2dd;
    undefined field_0x2de;
    undefined field_0x2df;
    undefined field_0x2e0;
    undefined field_0x2e1;
    undefined field_0x2e2;
    undefined field_0x2e3;
    undefined field_0x2e4;
    undefined field_0x2e5;
    undefined field_0x2e6;
    undefined field_0x2e7;
    undefined field_0x2e8;
    undefined field_0x2e9;
    undefined field_0x2ea;
    undefined field_0x2eb;
    undefined field_0x2ec;
    undefined field_0x2ed;
    undefined field_0x2ee;
    undefined field_0x2ef;
    undefined field_0x2f0;
    undefined field_0x2f1;
    undefined field_0x2f2;
    undefined field_0x2f3;
    undefined field_0x2f4;
    undefined field_0x2f5;
    undefined field_0x2f6;
    undefined field_0x2f7;
    undefined field_0x2f8;
    undefined field_0x2f9;
    undefined field_0x2fa;
    undefined field_0x2fb;
    undefined field_0x2fc;
    undefined field_0x2fd;
    undefined field_0x2fe;
    undefined field_0x2ff;
    struct vector4_t translate;
    struct vector4_t translate2;
    struct vector4_t unknownVec;
    float rotate_y;
    float rotate_x;
    struct bayoActor_t * actor;
    int unknownFieldDueToFlag4;
    int setToOne;
};

typedef struct bayoCloth_t bayoCloth_t, *PbayoCloth_t;

typedef struct bayoClothItem_t bayoClothItem_t, *PbayoClothItem_t;

typedef struct clpItem_t clpItem_t, *PclpItem_t;

typedef struct bayoHitItem_t bayoHitItem_t, *PbayoHitItem_t;

typedef struct bayoWindItem_t bayoWindItem_t, *PbayoWindItem_t;

typedef struct clwItem_t clwItem_t, *PclwItem_t;

struct bayoWindItem_t {
    dword windType;
    dword partsNo;
    dword field_8;
    dword field_C;
    struct vector4_t offset;
    struct vector4_t offset2;
    float radius;
    float power;
    float timer;
    float swingRate;
    float swingSpd;
    float delayMax;
    dword field_48;
    dword field_4C;
    struct vector4_t field_50;
    struct vector4_t field_60;
    dword field_70;
    dword field_74;
    dword field_78;
    dword field_7C;
};

struct bayoCloth_t {
    int clpInitialized;
    dword field_4;
    dword field_8;
    dword field_C;
    void * clpHandle;
    dword clpItemNum;
    struct bayoClothItem_t * pClpItems;
    struct clpItem_t * pClpItemsBis;
    int clhItemNum;
    struct bayoHitItem_t * pClhItems;
    int clwItemCount;
    dword field_2C;
    struct bayoWindItem_t windItems[16];
    int clwInited;
    struct clwItem_t * pClwItems;
    undefined field_0x838;
    undefined field_0x839;
    undefined field_0x83a;
    undefined field_0x83b;
    undefined field_0x83c;
    undefined field_0x83d;
    undefined field_0x83e;
    undefined field_0x83f;
    undefined field_0x840;
    undefined field_0x841;
    undefined field_0x842;
    undefined field_0x843;
    undefined field_0x844;
    undefined field_0x845;
    undefined field_0x846;
    undefined field_0x847;
    undefined field_0x848;
    undefined field_0x849;
    undefined field_0x84a;
    undefined field_0x84b;
    undefined field_0x84c;
    undefined field_0x84d;
    undefined field_0x84e;
    undefined field_0x84f;
    undefined field_0x850;
    undefined field_0x851;
    undefined field_0x852;
    undefined field_0x853;
    undefined field_0x854;
    undefined field_0x855;
    undefined field_0x856;
    undefined field_0x857;
    undefined field_0x858;
    undefined field_0x859;
    undefined field_0x85a;
    undefined field_0x85b;
    undefined field_0x85c;
    undefined field_0x85d;
    undefined field_0x85e;
    undefined field_0x85f;
    undefined field_0x860;
    undefined field_0x861;
    undefined field_0x862;
    undefined field_0x863;
    undefined field_0x864;
    undefined field_0x865;
    undefined field_0x866;
    undefined field_0x867;
    undefined field_0x868;
    undefined field_0x869;
    undefined field_0x86a;
    undefined field_0x86b;
    undefined field_0x86c;
    undefined field_0x86d;
    undefined field_0x86e;
    undefined field_0x86f;
    undefined field_0x870;
    undefined field_0x871;
    undefined field_0x872;
    undefined field_0x873;
    undefined field_0x874;
    undefined field_0x875;
    undefined field_0x876;
    undefined field_0x877;
    undefined field_0x878;
    undefined field_0x879;
    undefined field_0x87a;
    undefined field_0x87b;
    undefined field_0x87c;
    undefined field_0x87d;
    undefined field_0x87e;
    undefined field_0x87f;
    undefined field_0x880;
    undefined field_0x881;
    undefined field_0x882;
    undefined field_0x883;
    undefined field_0x884;
    undefined field_0x885;
    undefined field_0x886;
    undefined field_0x887;
    undefined field_0x888;
    undefined field_0x889;
    undefined field_0x88a;
    undefined field_0x88b;
    undefined field_0x88c;
    undefined field_0x88d;
    undefined field_0x88e;
    undefined field_0x88f;
    undefined field_0x890;
    undefined field_0x891;
    undefined field_0x892;
    undefined field_0x893;
    undefined field_0x894;
    undefined field_0x895;
    undefined field_0x896;
    undefined field_0x897;
    undefined field_0x898;
    undefined field_0x899;
    undefined field_0x89a;
    undefined field_0x89b;
    undefined field_0x89c;
    undefined field_0x89d;
    undefined field_0x89e;
    undefined field_0x89f;
    undefined field_0x8a0;
    undefined field_0x8a1;
    undefined field_0x8a2;
    undefined field_0x8a3;
    undefined field_0x8a4;
    undefined field_0x8a5;
    undefined field_0x8a6;
    undefined field_0x8a7;
    undefined field_0x8a8;
    undefined field_0x8a9;
    undefined field_0x8aa;
    undefined field_0x8ab;
    dword field_8AC;
    dword field_8B0;
    dword field_8B4;
    dword field_8B8;
    dword field_8BC;
    struct bayoActor_t * clpActor;
    struct bayoActor_t * clpActor2;
    struct bayoActor_t * clhActor;
    struct bayoActor_t * clwActor;
    float limitSpringRate;
    float spdRate;
    float stretchy;
    short bundleNum;
    short bundleNum2;
    dword field_8E0;
    float thick;
    dword field_8E8;
    dword field_8EC;
    struct vector4_t gravityVec;
    int gravityPartNo;
    float firstBundleRate;
    dword field_908;
    dword field_90C;
    struct vector4_t windVec;
    int windPartNo;
    dword field_924;
    dword field_928;
    dword field_92C;
    struct vector4_t windOffset;
    float windSin;
    float hitAdjustRate;
    dword field_948;
    dword field_94C;
    dword field_950;
    dword field_954;
    dword field_958;
    dword field_95C;
    dword field_960;
    dword field_964;
    dword field_968;
    dword field_96C;
    dword field_970;
    int sidePhysics;
    dword field_978;
    dword field_97C;
    dword field_980;
    undefined field_0x984;
    undefined field_0x985;
    undefined field_0x986;
    undefined field_0x987;
    undefined field_0x988;
    undefined field_0x989;
    undefined field_0x98a;
    undefined field_0x98b;
    undefined field_0x98c;
    undefined field_0x98d;
    undefined field_0x98e;
    undefined field_0x98f;
    undefined field_0x990;
    undefined field_0x991;
    undefined field_0x992;
    undefined field_0x993;
    undefined field_0x994;
    undefined field_0x995;
    undefined field_0x996;
    undefined field_0x997;
    undefined field_0x998;
    undefined field_0x999;
    undefined field_0x99a;
    undefined field_0x99b;
    undefined field_0x99c;
    undefined field_0x99d;
    undefined field_0x99e;
    undefined field_0x99f;
    undefined field_0x9a0;
    undefined field_0x9a1;
    undefined field_0x9a2;
    undefined field_0x9a3;
    undefined field_0x9a4;
    undefined field_0x9a5;
    undefined field_0x9a6;
    undefined field_0x9a7;
    undefined field_0x9a8;
    undefined field_0x9a9;
    undefined field_0x9aa;
    undefined field_0x9ab;
    undefined field_0x9ac;
    undefined field_0x9ad;
    undefined field_0x9ae;
    undefined field_0x9af;
    undefined field_0x9b0;
    undefined field_0x9b1;
    undefined field_0x9b2;
    undefined field_0x9b3;
    undefined field_0x9b4;
    undefined field_0x9b5;
    undefined field_0x9b6;
    undefined field_0x9b7;
    undefined field_0x9b8;
    undefined field_0x9b9;
    undefined field_0x9ba;
    undefined field_0x9bb;
    undefined field_0x9bc;
    undefined field_0x9bd;
    undefined field_0x9be;
    undefined field_0x9bf;
    undefined field_0x9c0;
    undefined field_0x9c1;
    undefined field_0x9c2;
    undefined field_0x9c3;
    undefined field_0x9c4;
    undefined field_0x9c5;
    undefined field_0x9c6;
    undefined field_0x9c7;
    undefined field_0x9c8;
    undefined field_0x9c9;
    undefined field_0x9ca;
    undefined field_0x9cb;
    undefined field_0x9cc;
    undefined field_0x9cd;
    undefined field_0x9ce;
    undefined field_0x9cf;
    undefined field_0x9d0;
    undefined field_0x9d1;
    undefined field_0x9d2;
    undefined field_0x9d3;
    undefined field_0x9d4;
    undefined field_0x9d5;
    undefined field_0x9d6;
    undefined field_0x9d7;
    undefined field_0x9d8;
    undefined field_0x9d9;
    undefined field_0x9da;
    undefined field_0x9db;
    undefined field_0x9dc;
    undefined field_0x9dd;
    undefined field_0x9de;
    undefined field_0x9df;
    undefined field_0x9e0;
    undefined field_0x9e1;
    undefined field_0x9e2;
    undefined field_0x9e3;
    undefined field_0x9e4;
    undefined field_0x9e5;
    undefined field_0x9e6;
    undefined field_0x9e7;
    undefined field_0x9e8;
    undefined field_0x9e9;
    undefined field_0x9ea;
    undefined field_0x9eb;
    undefined field_0x9ec;
    undefined field_0x9ed;
    undefined field_0x9ee;
    undefined field_0x9ef;
    undefined field_0x9f0;
    undefined field_0x9f1;
    undefined field_0x9f2;
    undefined field_0x9f3;
    undefined field_0x9f4;
    undefined field_0x9f5;
    undefined field_0x9f6;
    undefined field_0x9f7;
    undefined field_0x9f8;
    undefined field_0x9f9;
    undefined field_0x9fa;
    undefined field_0x9fb;
    undefined field_0x9fc;
    undefined field_0x9fd;
    undefined field_0x9fe;
    undefined field_0x9ff;
    undefined field_0xa00;
    undefined field_0xa01;
    undefined field_0xa02;
    undefined field_0xa03;
    undefined field_0xa04;
    undefined field_0xa05;
    undefined field_0xa06;
    undefined field_0xa07;
    undefined field_0xa08;
    undefined field_0xa09;
    undefined field_0xa0a;
    undefined field_0xa0b;
    undefined field_0xa0c;
    undefined field_0xa0d;
    undefined field_0xa0e;
    undefined field_0xa0f;
    undefined field_0xa10;
    undefined field_0xa11;
    undefined field_0xa12;
    undefined field_0xa13;
    undefined field_0xa14;
    undefined field_0xa15;
    undefined field_0xa16;
    undefined field_0xa17;
    undefined field_0xa18;
    undefined field_0xa19;
    undefined field_0xa1a;
    undefined field_0xa1b;
    undefined field_0xa1c;
    undefined field_0xa1d;
    undefined field_0xa1e;
    undefined field_0xa1f;
    undefined field_0xa20;
    undefined field_0xa21;
    undefined field_0xa22;
    undefined field_0xa23;
    undefined field_0xa24;
    undefined field_0xa25;
    undefined field_0xa26;
    undefined field_0xa27;
    undefined field_0xa28;
    undefined field_0xa29;
    undefined field_0xa2a;
    undefined field_0xa2b;
    undefined field_0xa2c;
    undefined field_0xa2d;
    undefined field_0xa2e;
    undefined field_0xa2f;
    undefined field_0xa30;
    undefined field_0xa31;
    undefined field_0xa32;
    undefined field_0xa33;
    undefined field_0xa34;
    undefined field_0xa35;
    undefined field_0xa36;
    undefined field_0xa37;
    undefined field_0xa38;
    undefined field_0xa39;
    undefined field_0xa3a;
    undefined field_0xa3b;
    undefined field_0xa3c;
    undefined field_0xa3d;
    undefined field_0xa3e;
    undefined field_0xa3f;
    undefined field_0xa40;
    undefined field_0xa41;
    undefined field_0xa42;
    undefined field_0xa43;
    undefined field_0xa44;
    undefined field_0xa45;
    undefined field_0xa46;
    undefined field_0xa47;
    undefined field_0xa48;
    undefined field_0xa49;
    undefined field_0xa4a;
    undefined field_0xa4b;
    undefined field_0xa4c;
    undefined field_0xa4d;
    undefined field_0xa4e;
    undefined field_0xa4f;
    undefined field_0xa50;
    undefined field_0xa51;
    undefined field_0xa52;
    undefined field_0xa53;
    undefined field_0xa54;
    undefined field_0xa55;
    undefined field_0xa56;
    undefined field_0xa57;
    undefined field_0xa58;
    undefined field_0xa59;
    undefined field_0xa5a;
    undefined field_0xa5b;
    undefined field_0xa5c;
    undefined field_0xa5d;
    undefined field_0xa5e;
    undefined field_0xa5f;
    undefined field_0xa60;
    undefined field_0xa61;
    undefined field_0xa62;
    undefined field_0xa63;
    undefined field_0xa64;
    undefined field_0xa65;
    undefined field_0xa66;
    undefined field_0xa67;
    undefined field_0xa68;
    undefined field_0xa69;
    undefined field_0xa6a;
    undefined field_0xa6b;
    undefined field_0xa6c;
    undefined field_0xa6d;
    undefined field_0xa6e;
    undefined field_0xa6f;
    undefined field_0xa70;
    undefined field_0xa71;
    undefined field_0xa72;
    undefined field_0xa73;
    undefined field_0xa74;
    undefined field_0xa75;
    undefined field_0xa76;
    undefined field_0xa77;
    undefined field_0xa78;
    undefined field_0xa79;
    undefined field_0xa7a;
    undefined field_0xa7b;
    undefined field_0xa7c;
    undefined field_0xa7d;
    undefined field_0xa7e;
    undefined field_0xa7f;
    undefined field_0xa80;
    undefined field_0xa81;
    undefined field_0xa82;
    undefined field_0xa83;
    undefined field_0xa84;
    undefined field_0xa85;
    undefined field_0xa86;
    undefined field_0xa87;
    undefined field_0xa88;
    undefined field_0xa89;
    undefined field_0xa8a;
    undefined field_0xa8b;
    undefined field_0xa8c;
    undefined field_0xa8d;
    undefined field_0xa8e;
    undefined field_0xa8f;
    undefined field_0xa90;
    undefined field_0xa91;
    undefined field_0xa92;
    undefined field_0xa93;
    undefined field_0xa94;
    undefined field_0xa95;
    undefined field_0xa96;
    undefined field_0xa97;
    undefined field_0xa98;
    undefined field_0xa99;
    undefined field_0xa9a;
    undefined field_0xa9b;
    undefined field_0xa9c;
    undefined field_0xa9d;
    undefined field_0xa9e;
    undefined field_0xa9f;
    undefined field_0xaa0;
    undefined field_0xaa1;
    undefined field_0xaa2;
    undefined field_0xaa3;
    undefined field_0xaa4;
    undefined field_0xaa5;
    undefined field_0xaa6;
    undefined field_0xaa7;
    undefined field_0xaa8;
    undefined field_0xaa9;
    undefined field_0xaaa;
    undefined field_0xaab;
    undefined field_0xaac;
    undefined field_0xaad;
    undefined field_0xaae;
    undefined field_0xaaf;
    undefined field_0xab0;
    undefined field_0xab1;
    undefined field_0xab2;
    undefined field_0xab3;
    undefined field_0xab4;
    undefined field_0xab5;
    undefined field_0xab6;
    undefined field_0xab7;
    undefined field_0xab8;
    undefined field_0xab9;
    undefined field_0xaba;
    undefined field_0xabb;
    undefined field_0xabc;
    undefined field_0xabd;
    undefined field_0xabe;
    undefined field_0xabf;
    undefined field_0xac0;
    undefined field_0xac1;
    undefined field_0xac2;
    undefined field_0xac3;
    undefined field_0xac4;
    undefined field_0xac5;
    undefined field_0xac6;
    undefined field_0xac7;
    undefined field_0xac8;
    undefined field_0xac9;
    undefined field_0xaca;
    undefined field_0xacb;
    undefined field_0xacc;
    undefined field_0xacd;
    undefined field_0xace;
    undefined field_0xacf;
    undefined field_0xad0;
    undefined field_0xad1;
    undefined field_0xad2;
    undefined field_0xad3;
    undefined field_0xad4;
    undefined field_0xad5;
    undefined field_0xad6;
    undefined field_0xad7;
    undefined field_0xad8;
    undefined field_0xad9;
    undefined field_0xada;
    undefined field_0xadb;
    undefined field_0xadc;
    undefined field_0xadd;
    undefined field_0xade;
    undefined field_0xadf;
    undefined field_0xae0;
    undefined field_0xae1;
    undefined field_0xae2;
    undefined field_0xae3;
    undefined field_0xae4;
    undefined field_0xae5;
    undefined field_0xae6;
    undefined field_0xae7;
    undefined field_0xae8;
    undefined field_0xae9;
    undefined field_0xaea;
    undefined field_0xaeb;
    undefined field_0xaec;
    undefined field_0xaed;
    undefined field_0xaee;
    undefined field_0xaef;
    undefined field_0xaf0;
    undefined field_0xaf1;
    undefined field_0xaf2;
    undefined field_0xaf3;
    undefined field_0xaf4;
    undefined field_0xaf5;
    undefined field_0xaf6;
    undefined field_0xaf7;
    undefined field_0xaf8;
    undefined field_0xaf9;
    undefined field_0xafa;
    undefined field_0xafb;
    undefined field_0xafc;
    undefined field_0xafd;
    undefined field_0xafe;
    undefined field_0xaff;
    undefined field_0xb00;
    undefined field_0xb01;
    undefined field_0xb02;
    undefined field_0xb03;
    undefined field_0xb04;
    undefined field_0xb05;
    undefined field_0xb06;
    undefined field_0xb07;
    undefined field_0xb08;
    undefined field_0xb09;
    undefined field_0xb0a;
    undefined field_0xb0b;
    undefined field_0xb0c;
    undefined field_0xb0d;
    undefined field_0xb0e;
    undefined field_0xb0f;
    undefined field_0xb10;
    undefined field_0xb11;
    undefined field_0xb12;
    undefined field_0xb13;
    undefined field_0xb14;
    undefined field_0xb15;
    undefined field_0xb16;
    undefined field_0xb17;
    undefined field_0xb18;
    undefined field_0xb19;
    undefined field_0xb1a;
    undefined field_0xb1b;
    undefined field_0xb1c;
    undefined field_0xb1d;
    undefined field_0xb1e;
    undefined field_0xb1f;
    undefined field_0xb20;
    undefined field_0xb21;
    undefined field_0xb22;
    undefined field_0xb23;
    undefined field_0xb24;
    undefined field_0xb25;
    undefined field_0xb26;
    undefined field_0xb27;
    undefined field_0xb28;
    undefined field_0xb29;
    undefined field_0xb2a;
    undefined field_0xb2b;
    undefined field_0xb2c;
    undefined field_0xb2d;
    undefined field_0xb2e;
    undefined field_0xb2f;
    undefined field_0xb30;
    undefined field_0xb31;
    undefined field_0xb32;
    undefined field_0xb33;
    undefined field_0xb34;
    undefined field_0xb35;
    undefined field_0xb36;
    undefined field_0xb37;
    undefined field_0xb38;
    undefined field_0xb39;
    undefined field_0xb3a;
    undefined field_0xb3b;
    undefined field_0xb3c;
    undefined field_0xb3d;
    undefined field_0xb3e;
    undefined field_0xb3f;
    undefined field_0xb40;
    undefined field_0xb41;
    undefined field_0xb42;
    undefined field_0xb43;
    undefined field_0xb44;
    undefined field_0xb45;
    undefined field_0xb46;
    undefined field_0xb47;
    undefined field_0xb48;
    undefined field_0xb49;
    undefined field_0xb4a;
    undefined field_0xb4b;
    undefined field_0xb4c;
    undefined field_0xb4d;
    undefined field_0xb4e;
    undefined field_0xb4f;
    undefined field_0xb50;
    undefined field_0xb51;
    undefined field_0xb52;
    undefined field_0xb53;
    undefined field_0xb54;
    undefined field_0xb55;
    undefined field_0xb56;
    undefined field_0xb57;
    undefined field_0xb58;
    undefined field_0xb59;
    undefined field_0xb5a;
    undefined field_0xb5b;
    undefined field_0xb5c;
    undefined field_0xb5d;
    undefined field_0xb5e;
    undefined field_0xb5f;
    undefined field_0xb60;
    undefined field_0xb61;
    undefined field_0xb62;
    undefined field_0xb63;
    undefined field_0xb64;
    undefined field_0xb65;
    undefined field_0xb66;
    undefined field_0xb67;
    undefined field_0xb68;
    undefined field_0xb69;
    undefined field_0xb6a;
    undefined field_0xb6b;
    undefined field_0xb6c;
    undefined field_0xb6d;
    undefined field_0xb6e;
    undefined field_0xb6f;
    undefined field_0xb70;
    undefined field_0xb71;
    undefined field_0xb72;
    undefined field_0xb73;
    undefined field_0xb74;
    undefined field_0xb75;
    undefined field_0xb76;
    undefined field_0xb77;
    undefined field_0xb78;
    undefined field_0xb79;
    undefined field_0xb7a;
    undefined field_0xb7b;
    undefined field_0xb7c;
    undefined field_0xb7d;
    undefined field_0xb7e;
    undefined field_0xb7f;
    undefined field_0xb80;
    undefined field_0xb81;
    undefined field_0xb82;
    undefined field_0xb83;
    undefined field_0xb84;
    undefined field_0xb85;
    undefined field_0xb86;
    undefined field_0xb87;
    undefined field_0xb88;
    undefined field_0xb89;
    undefined field_0xb8a;
    undefined field_0xb8b;
    undefined field_0xb8c;
    undefined field_0xb8d;
    undefined field_0xb8e;
    undefined field_0xb8f;
    undefined field_0xb90;
    undefined field_0xb91;
    undefined field_0xb92;
    undefined field_0xb93;
    undefined field_0xb94;
    undefined field_0xb95;
    undefined field_0xb96;
    undefined field_0xb97;
    undefined field_0xb98;
    undefined field_0xb99;
    undefined field_0xb9a;
    undefined field_0xb9b;
    undefined field_0xb9c;
    undefined field_0xb9d;
    undefined field_0xb9e;
    undefined field_0xb9f;
    undefined field_0xba0;
    undefined field_0xba1;
    undefined field_0xba2;
    undefined field_0xba3;
    undefined field_0xba4;
    undefined field_0xba5;
    undefined field_0xba6;
    undefined field_0xba7;
    undefined field_0xba8;
    undefined field_0xba9;
    undefined field_0xbaa;
    undefined field_0xbab;
    undefined field_0xbac;
    undefined field_0xbad;
    undefined field_0xbae;
    undefined field_0xbaf;
    undefined field_0xbb0;
    undefined field_0xbb1;
    undefined field_0xbb2;
    undefined field_0xbb3;
    undefined field_0xbb4;
    undefined field_0xbb5;
    undefined field_0xbb6;
    undefined field_0xbb7;
    undefined field_0xbb8;
    undefined field_0xbb9;
    undefined field_0xbba;
    undefined field_0xbbb;
    undefined field_0xbbc;
    undefined field_0xbbd;
    undefined field_0xbbe;
    undefined field_0xbbf;
    undefined field_0xbc0;
    undefined field_0xbc1;
    undefined field_0xbc2;
    undefined field_0xbc3;
    undefined field_0xbc4;
    undefined field_0xbc5;
    undefined field_0xbc6;
    undefined field_0xbc7;
    undefined field_0xbc8;
    undefined field_0xbc9;
    undefined field_0xbca;
    undefined field_0xbcb;
    undefined field_0xbcc;
    undefined field_0xbcd;
    undefined field_0xbce;
    undefined field_0xbcf;
    undefined field_0xbd0;
    undefined field_0xbd1;
    undefined field_0xbd2;
    undefined field_0xbd3;
    undefined field_0xbd4;
    undefined field_0xbd5;
    undefined field_0xbd6;
    undefined field_0xbd7;
    undefined field_0xbd8;
    undefined field_0xbd9;
    undefined field_0xbda;
    undefined field_0xbdb;
    undefined field_0xbdc;
    undefined field_0xbdd;
    undefined field_0xbde;
    undefined field_0xbdf;
    undefined field_0xbe0;
    undefined field_0xbe1;
    undefined field_0xbe2;
    undefined field_0xbe3;
    undefined field_0xbe4;
    undefined field_0xbe5;
    undefined field_0xbe6;
    undefined field_0xbe7;
    undefined field_0xbe8;
    undefined field_0xbe9;
    undefined field_0xbea;
    undefined field_0xbeb;
    undefined field_0xbec;
    undefined field_0xbed;
    undefined field_0xbee;
    undefined field_0xbef;
    undefined field_0xbf0;
    undefined field_0xbf1;
    undefined field_0xbf2;
    undefined field_0xbf3;
    undefined field_0xbf4;
    undefined field_0xbf5;
    undefined field_0xbf6;
    undefined field_0xbf7;
    undefined field_0xbf8;
    undefined field_0xbf9;
    undefined field_0xbfa;
    undefined field_0xbfb;
    undefined field_0xbfc;
    undefined field_0xbfd;
    undefined field_0xbfe;
    undefined field_0xbff;
    undefined field_0xc00;
    undefined field_0xc01;
    undefined field_0xc02;
    undefined field_0xc03;
    undefined field_0xc04;
    undefined field_0xc05;
    undefined field_0xc06;
    undefined field_0xc07;
    undefined field_0xc08;
    undefined field_0xc09;
    undefined field_0xc0a;
    undefined field_0xc0b;
    undefined field_0xc0c;
    undefined field_0xc0d;
    undefined field_0xc0e;
    undefined field_0xc0f;
    undefined field_0xc10;
    undefined field_0xc11;
    undefined field_0xc12;
    undefined field_0xc13;
    undefined field_0xc14;
    undefined field_0xc15;
    undefined field_0xc16;
    undefined field_0xc17;
    undefined field_0xc18;
    undefined field_0xc19;
    undefined field_0xc1a;
    undefined field_0xc1b;
    undefined field_0xc1c;
    undefined field_0xc1d;
    undefined field_0xc1e;
    undefined field_0xc1f;
    undefined field_0xc20;
    undefined field_0xc21;
    undefined field_0xc22;
    undefined field_0xc23;
    undefined field_0xc24;
    undefined field_0xc25;
    undefined field_0xc26;
    undefined field_0xc27;
    undefined field_0xc28;
    undefined field_0xc29;
    undefined field_0xc2a;
    undefined field_0xc2b;
    undefined field_0xc2c;
    undefined field_0xc2d;
    undefined field_0xc2e;
    undefined field_0xc2f;
    undefined field_0xc30;
    undefined field_0xc31;
    undefined field_0xc32;
    undefined field_0xc33;
    undefined field_0xc34;
    undefined field_0xc35;
    undefined field_0xc36;
    undefined field_0xc37;
    undefined field_0xc38;
    undefined field_0xc39;
    undefined field_0xc3a;
    undefined field_0xc3b;
    undefined field_0xc3c;
    undefined field_0xc3d;
    undefined field_0xc3e;
    undefined field_0xc3f;
    undefined field_0xc40;
    undefined field_0xc41;
    undefined field_0xc42;
    undefined field_0xc43;
    undefined field_0xc44;
    undefined field_0xc45;
    undefined field_0xc46;
    undefined field_0xc47;
    undefined field_0xc48;
    undefined field_0xc49;
    undefined field_0xc4a;
    undefined field_0xc4b;
    undefined field_0xc4c;
    undefined field_0xc4d;
    undefined field_0xc4e;
    undefined field_0xc4f;
    undefined field_0xc50;
    undefined field_0xc51;
    undefined field_0xc52;
    undefined field_0xc53;
    undefined field_0xc54;
    undefined field_0xc55;
    undefined field_0xc56;
    undefined field_0xc57;
    undefined field_0xc58;
    undefined field_0xc59;
    undefined field_0xc5a;
    undefined field_0xc5b;
    undefined field_0xc5c;
    undefined field_0xc5d;
    undefined field_0xc5e;
    undefined field_0xc5f;
    undefined field_0xc60;
    undefined field_0xc61;
    undefined field_0xc62;
    undefined field_0xc63;
    undefined field_0xc64;
    undefined field_0xc65;
    undefined field_0xc66;
    undefined field_0xc67;
    undefined field_0xc68;
    undefined field_0xc69;
    undefined field_0xc6a;
    undefined field_0xc6b;
    undefined field_0xc6c;
    undefined field_0xc6d;
    undefined field_0xc6e;
    undefined field_0xc6f;
    undefined field_0xc70;
    undefined field_0xc71;
    undefined field_0xc72;
    undefined field_0xc73;
    undefined field_0xc74;
    undefined field_0xc75;
    undefined field_0xc76;
    undefined field_0xc77;
    undefined field_0xc78;
    undefined field_0xc79;
    undefined field_0xc7a;
    undefined field_0xc7b;
    undefined field_0xc7c;
    undefined field_0xc7d;
    undefined field_0xc7e;
    undefined field_0xc7f;
    undefined field_0xc80;
    undefined field_0xc81;
    undefined field_0xc82;
    undefined field_0xc83;
    undefined field_0xc84;
    undefined field_0xc85;
    undefined field_0xc86;
    undefined field_0xc87;
    undefined field_0xc88;
    undefined field_0xc89;
    undefined field_0xc8a;
    undefined field_0xc8b;
    undefined field_0xc8c;
    undefined field_0xc8d;
    undefined field_0xc8e;
    undefined field_0xc8f;
    undefined field_0xc90;
    undefined field_0xc91;
    undefined field_0xc92;
    undefined field_0xc93;
    undefined field_0xc94;
    undefined field_0xc95;
    undefined field_0xc96;
    undefined field_0xc97;
    undefined field_0xc98;
    undefined field_0xc99;
    undefined field_0xc9a;
    undefined field_0xc9b;
    undefined field_0xc9c;
    undefined field_0xc9d;
    undefined field_0xc9e;
    undefined field_0xc9f;
    undefined field_0xca0;
    undefined field_0xca1;
    undefined field_0xca2;
    undefined field_0xca3;
    undefined field_0xca4;
    undefined field_0xca5;
    undefined field_0xca6;
    undefined field_0xca7;
    undefined field_0xca8;
    undefined field_0xca9;
    undefined field_0xcaa;
    undefined field_0xcab;
    undefined field_0xcac;
    undefined field_0xcad;
    undefined field_0xcae;
    undefined field_0xcaf;
    undefined field_0xcb0;
    undefined field_0xcb1;
    undefined field_0xcb2;
    undefined field_0xcb3;
    undefined field_0xcb4;
    undefined field_0xcb5;
    undefined field_0xcb6;
    undefined field_0xcb7;
    undefined field_0xcb8;
    undefined field_0xcb9;
    undefined field_0xcba;
    undefined field_0xcbb;
    undefined field_0xcbc;
    undefined field_0xcbd;
    undefined field_0xcbe;
    undefined field_0xcbf;
    undefined field_0xcc0;
    undefined field_0xcc1;
    undefined field_0xcc2;
    undefined field_0xcc3;
    undefined field_0xcc4;
    undefined field_0xcc5;
    undefined field_0xcc6;
    undefined field_0xcc7;
    undefined field_0xcc8;
    undefined field_0xcc9;
    undefined field_0xcca;
    undefined field_0xccb;
    undefined field_0xccc;
    undefined field_0xccd;
    undefined field_0xcce;
    undefined field_0xccf;
    undefined field_0xcd0;
    undefined field_0xcd1;
    undefined field_0xcd2;
    undefined field_0xcd3;
    undefined field_0xcd4;
    undefined field_0xcd5;
    undefined field_0xcd6;
    undefined field_0xcd7;
    undefined field_0xcd8;
    undefined field_0xcd9;
    undefined field_0xcda;
    undefined field_0xcdb;
    undefined field_0xcdc;
    undefined field_0xcdd;
    undefined field_0xcde;
    undefined field_0xcdf;
    undefined field_0xce0;
    undefined field_0xce1;
    undefined field_0xce2;
    undefined field_0xce3;
    undefined field_0xce4;
    undefined field_0xce5;
    undefined field_0xce6;
    undefined field_0xce7;
    undefined field_0xce8;
    undefined field_0xce9;
    undefined field_0xcea;
    undefined field_0xceb;
    undefined field_0xcec;
    undefined field_0xced;
    undefined field_0xcee;
    undefined field_0xcef;
    undefined field_0xcf0;
    undefined field_0xcf1;
    undefined field_0xcf2;
    undefined field_0xcf3;
    undefined field_0xcf4;
    undefined field_0xcf5;
    undefined field_0xcf6;
    undefined field_0xcf7;
    undefined field_0xcf8;
    undefined field_0xcf9;
    undefined field_0xcfa;
    undefined field_0xcfb;
    undefined field_0xcfc;
    undefined field_0xcfd;
    undefined field_0xcfe;
    undefined field_0xcff;
    undefined field_0xd00;
    undefined field_0xd01;
    undefined field_0xd02;
    undefined field_0xd03;
    undefined field_0xd04;
    undefined field_0xd05;
    undefined field_0xd06;
    undefined field_0xd07;
    undefined field_0xd08;
    undefined field_0xd09;
    undefined field_0xd0a;
    undefined field_0xd0b;
    undefined field_0xd0c;
    undefined field_0xd0d;
    undefined field_0xd0e;
    undefined field_0xd0f;
    undefined field_0xd10;
    undefined field_0xd11;
    undefined field_0xd12;
    undefined field_0xd13;
    undefined field_0xd14;
    undefined field_0xd15;
    undefined field_0xd16;
    undefined field_0xd17;
    undefined field_0xd18;
    undefined field_0xd19;
    undefined field_0xd1a;
    undefined field_0xd1b;
    undefined field_0xd1c;
    undefined field_0xd1d;
    undefined field_0xd1e;
    undefined field_0xd1f;
};

struct clwItem_t {
    int windType;
    int partsNo;
    struct vector3_t offset;
    struct vector3_t offset2;
    float radius;
    float power;
    float timer;
    float swingRate;
    float swingSpd;
    float delayMax;
};

struct clpItem_t {
    short no;
    short noUp;
    short noDown;
    short noSide;
    short noPoly;
    short noFix;
    float rotLimit;
    struct vector3_t offset;
};

struct bayoHitItem_t {
    short p1;
    short p2;
    float weight;
    float radius;
    dword field_C;
    struct vector4_t offset;
    struct vector4_t offset2;
    struct vector4_t unknownVector;
};

struct bayoClothItem_t {
    short no;
    short noUp;
    short noDown;
    short noSide;
    short noPoly;
    short noFix;
    float distanceToParent;
    float distanceToSide;
    dword field_14;
    dword field_18;
    float angle;
    struct vector4_t offset;
    struct vector4_t unitVector;
    struct vector4_t unknownVector;
    struct vector4_t transformedOffset;
    struct vector4_t transformedOffsetBis;
    dword field_70;
    dword field_74;
    dword field_78;
    dword field_7C;
    dword field_80;
    dword field_84;
    dword field_88;
    dword field_8C;
    dword field_90;
    dword field_94;
    dword field_98;
    dword field_9C;
    struct vector4_t field_A0;
    struct vector4_t * pParentTransformedOffset;
    struct vector4_t * pSideTransformedOffset;
    struct vector4_t * pParentField_A0;
    struct vector4_t * pSideField_A0;
    struct vector4_t * pPolyParentTransformedOffset;
    struct vector4_t * pPolyTransformedOffset;
    float coeff;
    float sideCoeff;
    float rotLimit;
    struct bayoBone_t * pBone;
    struct bayoBone_t * boneFix;
    dword field_DC;
};

typedef struct bayoMaterialVectorTable_t bayoMaterialVectorTable_t, *PbayoMaterialVectorTable_t;

struct bayoMaterialVectorTable_t {
    struct bayoMaterialVectorTableItem_t * vectors[189];
};

typedef struct bayoMeshInfos_t bayoMeshInfos_t, *PbayoMeshInfos_t;

struct bayoMeshInfos_t {
    struct vector3_t center;
    float height;
    float radius;
    dword numBatch;
    struct vector3_t corner2;
    struct vector3_t corner1;
    char * pName;
    float unknown1;
    float unknown2;
    dword meshFlag_0x40000000;
};

typedef struct bayoSamplerCache_t bayoSamplerCache_t, *PbayoSamplerCache_t;

typedef struct bayoSamplerCacheItem_t bayoSamplerCacheItem_t, *PbayoSamplerCacheItem_t;

typedef struct bayoSpecialSamplerCacheItem_t bayoSpecialSamplerCacheItem_t, *PbayoSpecialSamplerCacheItem_t;

struct bayoSamplerCacheItem_t {
    uint samplerID;
    uint sampler[4];
    uint realSamplerID;
};

struct bayoSpecialSamplerCacheItem_t {
    uint samplerID;
    uint sampler[4];
};

struct bayoSamplerCache_t {
    struct bayoSamplerCacheItem_t systemSamplers[96];
    struct bayoSpecialSamplerCacheItem_t specialSamplers[16];
    struct bayoSamplerCacheItem_t levelSamplers[11];
    struct bayoSamplerCacheItem_t defaultSampler;
};

typedef struct bayoScene_t bayoScene_t, *PbayoScene_t;

struct bayoScene_t {
    dword field_0;
    dword field_4;
    struct bayoCamera_t * pCamera;
    dword field_C;
};

typedef struct bayoTextureCache_t bayoTextureCache_t, *PbayoTextureCache_t;

struct bayoTextureCache_t {
    struct bayoTextureCacheItem_t items[2048];
};

typedef struct bayoViewport_t bayoViewport_t, *PbayoViewport_t;

struct bayoViewport_t {
    int x;
    int y;
    int width;
    int height;
    float minZ;
    float maxZ;
};

typedef struct bayoWtb_t bayoWtb_t, *PbayoWtb_t;

typedef struct wtbHeader_t wtbHeader_t, *PwtbHeader_t;

struct bayoWtb_t {
    struct wtbHeader_t * pWtbHeader;
};

struct wtbHeader_t {
    uint id;
    uint unknown;
    uint numTex;
    uint offsetTextureOffsets;
    uint offsetTextureSizes;
    uint offsetTextureFlags;
};

typedef struct clhItem_t clhItem_t, *PclhItem_t;

struct clhItem_t {
    short p1;
    short p2;
    float weight;
    float radius;
    struct vector3_t offset;
    struct vector3_t offset2;
};

typedef struct clpHeader_t clpHeader_t, *PclpHeader_t;

struct clpHeader_t {
    int num;
    float limitSpringRate;
    float spdRate;
    float stretchy;
    short bundleNum;
    short bundleNum2;
    float thick;
    struct vector3_t gravityVec;
    int gravityPartNo;
    float firstBundleRate;
    struct vector3_t windVec;
    int windPartNo;
    struct vector3_t windOffset;
    float windSin;
    float hitAdjustRate;
};

typedef struct expEntry_t expEntry_t, *PexpEntry_t;

typedef union expEntryUnion_t expEntryUnion_t, *PexpEntryUnion_t;

typedef struct expEntryBoneTrackInfo_t expEntryBoneTrackInfo_t, *PexpEntryBoneTrackInfo_t;

struct expEntryBoneTrackInfo_t {
    short boneIndex;
    uchar animationTrack;
    byte padding;
};

union expEntryUnion_t {
    struct expEntryBoneTrackInfo_t boneTrackInfo;
    float value;
};

struct expEntry_t {
    uint flags;
    union expEntryUnion_t entryUnion;
};

typedef struct expHeader_t expHeader_t, *PexpHeader_t;

struct expHeader_t {
    char id[4];
    dword field_4;
    uint offsetRecords;
    int numRecords;
};

typedef struct expRecord_t expRecord_t, *PexpRecord_t;

struct expRecord_t {
    ushort flags;
    short boneIndex;
    uchar animationTrack;
    uchar entryCount;
    uchar interpolationEntryCount;
    char interpolation;
    ushort numPoints;
    word field_A;
    uint offset;
    uint offsetInterpollation;
};

typedef struct motKey2_t motKey2_t, *PmotKey2_t;

struct motKey2_t {
    ushort frameIndex;
    word padding;
    float p;
    float m0;
    float m1;
};

typedef struct motKey3_t motKey3_t, *PmotKey3_t;

struct motKey3_t {
    ushort cp;
};

typedef struct motKey4_t motKey4_t, *PmotKey4_t;

struct motKey4_t {
    ushort index;
    ushort cp;
    ushort cm0;
    ushort cm1;
};

typedef struct motKey5_t motKey5_t, *PmotKey5_t;

struct motKey5_t {
    uchar cp;
};

typedef struct motKey6_t motKey6_t, *PmotKey6_t;

struct motKey6_t {
    uchar index;
    uchar cp;
    uchar cm0;
    uchar cm1;
};

typedef struct motKey7_t motKey7_t, *PmotKey7_t;

struct motKey7_t {
    ushort index;
    byte dummy;
    uchar cp;
    uchar cm0;
    uchar cm1;
};

typedef struct motLoadVectors_t motLoadVectors_t, *PmotLoadVectors_t;

struct motLoadVectors_t {
    float (* pLoadFunctions[8])(struct motHeader_t *, struct motRecord_t *, void * *, float, int, int, int);
};

typedef struct motValues3_t motValues3_t, *PmotValues3_t;

struct motValues3_t {
    float p;
    float dp;
};

typedef struct motValues4_t motValues4_t, *PmotValues4_t;

struct motValues4_t {
    float p;
    float dp;
    float m0;
    float dm0;
    float m1;
    float dm1;
};

typedef struct motValues5_t motValues5_t, *PmotValues5_t;

struct motValues5_t {
    float p;
    float cp;
};

typedef struct motValues6_t motValues6_t, *PmotValues6_t;

typedef ushort pghalf;

struct motValues6_t {
    pghalf p;
    pghalf dp;
    pghalf m0;
    pghalf dm0;
    pghalf m1;
    pghalf dm1;
};

typedef struct motValues7_t motValues7_t, *PmotValues7_t;

struct motValues7_t {
    pghalf p;
    pghalf dp;
    pghalf m0;
    pghalf dm0;
    pghalf m1;
    pghalf dm1;
};

typedef struct seqAttackTrack_t seqAttackTrack_t, *PseqAttackTrack_t;

struct seqAttackTrack_t {
    float startTime;
    float endTime;
    short attackNumber;
    char shape;
    char dir;
    short power;
    short layerNo;
    struct vector3_t offset;
    struct vector3_t rot;
    struct vector3_t size;
};

typedef struct seqEffectTrack_t seqEffectTrack_t, *PseqEffectTrack_t;

struct seqEffectTrack_t {
};

typedef struct seqFlagsTrack_t seqFlagsTrack_t, *PseqFlagsTrack_t;

struct seqFlagsTrack_t {
    float startTime;
    float endTime;
    uint flag0;
    uint flag1;
};

typedef struct seqHeader_t seqHeader_t, *PseqHeader_t;

struct seqHeader_t {
    uint speedTrackCount;
    uint speedTrackOffset;
    uint attackTrackCount;
    uint attackTrackOffset;
    uint seTrackCount;
    uint seTrackOffset;
    uint effectTrackCount;
    uint effectTrackEffect;
    uint flagsTrackCount;
    uint flagsTrackOffset;
};

typedef struct seqSeTrack_t seqSeTrack_t, *PseqSeTrack_t;

struct seqSeTrack_t {
    float startTime;
    int event;
    int partsNo;
    uint flag;
};

typedef struct seqSpeedTrack_t seqSpeedTrack_t, *PseqSpeedTrack_t;

struct seqSpeedTrack_t {
    float startTime;
    float endTime;
    float speed;
    uint seqFlag;
};

typedef struct wmbBatchHeader_t wmbBatchHeader_t, *PwmbBatchHeader_t;

struct wmbBatchHeader_t {
    ushort batchIdx;
    ushort id;
    ushort flags;
    ushort exMaterialID;
    uchar materialID;
    uchar hasBoneRefs;
    uchar unknownE1;
    uchar unknownE2;
    uint verexStart;
    uint vertexEnd;
    int primitiveType;
    uint indicesOffset;
    uint numIndices;
    int vertexOffset;
    dword field_24;
    dword field_28;
    dword field_2C;
    dword field_30;
    dword field_34;
    dword field_38;
    dword field_3C;
};

typedef struct wmbMeshBoundingBox_t wmbMeshBoundingBox_t, *PwmbMeshBoundingBox_t;

struct wmbMeshBoundingBox_t {
    struct vector3_t center;
    float height;
    struct vector3_t corner1;
    struct vector3_t corner2;
    float unknown1;
    float unknown2;
};

typedef struct wmbMeshHeader_t wmbMeshHeader_t, *PwmbMeshHeader_t;

struct wmbMeshHeader_t {
    ushort id;
    ushort numBatch;
    word field_4;
    word field_6;
    uint offsetBatchOffsets;
    uint flags;
    dword field_10;
    dword field_14;
    dword field_18;
    dword field_1C;
    char name[32];
    struct wmbMeshBoundingBox_t boundingBox;
};

